spring.application.name=drink-water-api

# Schema Initialization
spring.jpa.hibernate.ddl-auto=update

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/drink_water_db?createDatabaseIfNotExist=true&serverTimezone=UTC&useSSL=false
spring.datasource.username=username
spring.datasource.password=password

server.servlet.context-path=/api/v1

#debug=true
#logging.level.org.springframework.security=DEBUG

jwt.private.key=classpath:app.key
jwt.public.key=classpath:app.pub
