services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: drink_water_db
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      TZ: UTC
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
