services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: drink_water_db
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  postgres:
    image: postgres:16-alpine
    volumes:
      - postgres_kc:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: security
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

  keycloak:
    image: quay.io/keycloak/keycloak:26.0.5
    command: start
    environment:
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8080
      KC_HOSTNAME_STRICT_BACKCHANNEL: false
      KC_HTTP_ENABLED: true
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HEALTH_ENABLED: true
      KEYCLOAK_ADMIN: security
      KEYCLOAK_ADMIN_PASSWORD: security
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres/security
      KC_DB_USERNAME: admin
      KC_DB_PASSWORD: admin
    ports:
      - "8080:8080"
    restart: always
    depends_on:
      - postgres
#  drinkwater:
#    image: eduardokohn/drinkwaterapi
#    environment:
#      DATABASE_PASSWORD: password
#      DATABASE_URL: jdbc:postgresql://db:5432/drink_water_db?options\=-c%20TimeZone%3DUTC
#      DATABASE_USERNAME: username
#      JPA_HIBERNATE_DDL_AUTO: update
#      LOGGING_LEVEL_ROOT: error
#      KEYCLOAK_CLIENT_ID: admin-cli
#      KEYCLOAK_ISSUER_URI: http://keycloak:8080/realms/drinkwater
#      KEYCLOAK_JWK_SET_URI: http://keycloak:8080/realms/drinkwater/protocol/openid-connect/certs
#      KEYCLOAK_PASSWORD: admin
#      KEYCLOAK_REALM: drinkwater
#      KEYCLOAK_URL: http://keycloak:8080
#      KEYCLOAK_USERNAME: keycloak-manager
#    ports:
#      - "8081:8081"
#    restart: always
#    depends_on:
#      - postgres

volumes:
  postgres_data:
  postgres_kc: