services:
  drinkwater_db:
    container_name: drinkwater_db
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: drink_water_db
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  keycloak_db:
    container_name: keycloak_db
    image: postgres:16-alpine
    volumes:
      - postgres_kc:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: security
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

  auth_keycloak:
    container_name: auth_keycloak
    image: quay.io/keycloak/keycloak:26.0.7
    command: start --import-realm
    environment:
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8080
      KC_HOSTNAME_STRICT_BACKCHANNEL: false
      KC_HTTP_ENABLED: true
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_HEALTH_ENABLED: true
      #      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      #      KC_BOOTSTRAP_ADMIN_PASSWORD: password
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://keycloak_db/security
      KC_DB_USERNAME: admin
      KC_DB_PASSWORD: admin
    ports:
      - "8080:8080"
    volumes:
      - ../src/main/resources/keycloak-realms.json:/opt/keycloak/data/import/keycloak-realms.json
    depends_on:
      - keycloak_db

#  drinkwater_api:
#    container_name: drinkwater_api
#    image: eduardokohn/drinkwaterapi:latest
#    environment:
#      DATABASE_USERNAME: username
#      DATABASE_PASSWORD: password
#      DATABASE_URL: jdbc:postgresql://drinkwater_db:5432/drink_water_db?options\=-c%20TimeZone%3DUTC
#      JPA_HIBERNATE_DDL_AUTO: create-drop
#      LOGGING_LEVEL_ROOT: debug
#      KEYCLOAK_CLIENT_ID: drinkwaterapp
#      KEYCLOAK_ISSUER_URI: http://auth_keycloak:8080/realms/drinkwater
#      KEYCLOAK_JWK_SET_URI: http://auth_keycloak:8080/realms/drinkwater/protocol/openid-connect/certs
#      KEYCLOAK_PASSWORD: admin
#      KEYCLOAK_REALM: drinkwater
#      KEYCLOAK_URL: http://auth_keycloak:8080
#      KEYCLOAK_USERNAME: admin-drinkwater
#      BASE_URL: http://localhost:3000
#    ports:
#      - "8081:8081"
#    depends_on:
#      - keycloak_db

volumes:
  postgres_data:
  postgres_kc: