DELETE FROM water_intakes;
DELETE FROM alarm_settings;
DELETE FROM users;

ALTER TABLE users ALTER COLUMN id RESTART WITH 1;
ALTER TABLE alarm_settings ALTER COLUMN id RESTART WITH 1;
ALTER TABLE water_intakes ALTER COLUMN id RESTART WITH 1;
