CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id UUID NOT NULL UNIQUE,
    email VARCHAR(255) NOT NULL UNIQUE,
    first_name VARCHAR(255) NOT NULL,
    last_name VARCHAR(255) NOT NULL,
    birth_date DATE NOT NULL,
    biological_sex INTEGER NOT NULL,
    weight NUMERIC(10,2) NOT NULL,
    weight_unit INTEGER NOT NULL,
    height NUMERIC(10,2) NOT NULL,
    height_unit INTEGER NOT NULL
);

CREATE INDEX idx_user_public_id ON users(public_id);

CREATE TABLE alarm_settings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    goal INTEGER NOT NULL,
    interval_minutes INTEGER NOT NULL,
    daily_start_time TIME NOT NULL,
    daily_end_time TIME NOT NULL,
    user_id BIGINT NOT NULL UNIQUE REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE water_intakes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date_time_utc TIMESTAMP WITH TIME ZONE NOT NULL,
    volume INTEGER NOT NULL,
    volume_unit INTEGER NOT NULL,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    UNIQUE(user_id, date_time_utc)
);

CREATE INDEX idx_water_intakes_user_datetime
    ON water_intakes(user_id, date_time_utc DESC, id DESC);
